namespace RecoPaperTrader;

// Settings generated by your previous tool
public class BotSettings
{
    public string ConfigHash { get; set; } = "";
    public List<StrategySetting> Strategies { get; set; } = new();
    public Risk RiskBot { get; set; } = new();

    public class StrategySetting
    {
        public string Strategy { get; set; } = "";
        public string Timeframe { get; set; } = "";
        public double Accuracy { get; set; }
        public double AvgConfidence { get; set; }
        public double AvgNetReturnPct { get; set; }
        public double MedianNetReturnPct { get; set; }
        public double Expectancy { get; set; }
        public double PayoffRatio { get; set; }
        public double WinLossRatio { get; set; }
    }

    public class Risk
    {
        public decimal RiskPctPerTrade { get; set; }
        public decimal MaxDailyLossPct { get; set; }
        public int MaxOpenPositionsPerSymbol { get; set; }
        public int CooldownMinutesPerSymbol { get; set; }
    }
}
